services:
  postgres:
    image: postgres:17

    container_name: anand-portfolio-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: anand_portfolio
      POSTGRES_USER: portfolio_admin
      POSTGRES_PASSWORD: portfolio_password

    ports:
      - "5433:5432"

    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data

volumes:
  portfolio_postgres_data: